// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NilDevStudio.WebAPI.Data;

namespace NilDevStudio.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200922124241_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("NilDevStudio.WebAPI.Models.MyEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataEvent");

                    b.Property<string>("Local");

                    b.Property<string>("Lot");

                    b.Property<int>("QuantPeople");

                    b.Property<string>("theme");

                    b.HasKey("EventId");

                    b.ToTable("MyEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
